name: Deploy Vue MiniApp

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Node.js 20 (ОБЯЗАТЕЛЬНО для Vite)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # 4. Сборка Vue
      - name: Build project
        run: npm run build

      # 5. Установка Yandex Cloud CLI
      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      # 6. Авторизация через OAuth-токен
      - name: Auth Yandex Cloud
        run: |
          yc config set token ${{ secrets.YC_TOKEN }}

      # 7. Деплой в Object Storage
      - name: Deploy to Object Storage
        run: |
          yc storage s3 sync dist/ s3://miniappbuck/ --delete
